# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: marketdata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10marketdata.proto\x12\x10mirro.marketdata\"-\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\x03\x12\x10\n\x08quantity\x18\x02 \x01(\x03\"\x8e\x01\n\x11OrderBookSnapshot\x12\x13\n\x0b\x65vent_ts_ms\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12*\n\x04\x62ids\x18\x03 \x03(\x0b\x32\x1c.mirro.marketdata.PriceLevel\x12*\n\x04\x61sks\x18\x04 \x03(\x0b\x32\x1c.mirro.marketdata.PriceLevel\"\x83\x02\n\x08\x45nvelope\x12\x10\n\x08sequence\x18\x01 \x01(\x04\x12\x15\n\rpublish_ts_ms\x18\x02 \x01(\x03\x12\x15\n\rreplay_run_id\x18\x03 \x01(\t\x12\x13\n\x0b\x65vent_ts_ms\x18\x04 \x01(\x03\x12\x12\n\nreplay_seq\x18\x05 \x01(\x04\x12\x37\n\x08snapshot\x18\x06 \x01(\x0b\x32#.mirro.marketdata.OrderBookSnapshotH\x00\x12\x18\n\x0eraw_event_json\x18\x07 \x01(\x0cH\x00\x12\x30\n\twatermark\x18\x08 \x01(\x0b\x32\x1b.mirro.marketdata.WatermarkH\x00\x42\t\n\x07payload\")\n\tWatermark\x12\x1c\n\x14\x63ompleted_through_ms\x18\x01 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marketdata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRICELEVEL._serialized_start=38
  _PRICELEVEL._serialized_end=83
  _ORDERBOOKSNAPSHOT._serialized_start=86
  _ORDERBOOKSNAPSHOT._serialized_end=228
  _ENVELOPE._serialized_start=231
  _ENVELOPE._serialized_end=490
  _WATERMARK._serialized_start=492
  _WATERMARK._serialized_end=533
# @@protoc_insertion_point(module_scope)
